function filterStrings() {
    var characters = document.getElementById('characters').value.toLowerCase().split(',');
    var categoryTaylorSwift = document.getElementById('categoryTaylorSwift').checked;
    var categoryFearless = document.getElementById('categoryFearless').checked;
    var categorySpeakNow = document.getElementById('categorySpeakNow').checked;
    var categoryRed = document.getElementById('categoryRed').checked;
    var category1989 = document.getElementById('category1989').checked;
    var categoryReputation = document.getElementById('categoryReputation').checked;
    var categoryLover = document.getElementById('categoryLover').checked;
    var categoryFolklore = document.getElementById('categoryFolklore').checked;
    var categoryEvermore = document.getElementById('categoryEvermore').checked;
    var categoryMidnights = document.getElementById('categoryMidnights').checked;
    var categoryTortured = document.getElementById('categoryTortured').checked;
    var categoryMisc = document.getElementById('categoryMisc').checked;
    var resultsContainer = document.getElementById('results');
    resultsContainer.innerHTML = '';
  
    var strings = [
        { text: 'Taylor Swift', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Tim McGraw', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Picture To Burn', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Teardrops On My Guitar', category: 'Taylor Swift', type: 'Song title' },
        { text: 'A Place In This World', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Cold As You', category: 'Taylor Swift', type: 'Song title' },
        { text: 'The Outside', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Tied Together With A Smile', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Stay Beautiful', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Shouldve Said No', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Marys Song (Oh My My My)', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Our Song', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Im Only Me When Im With You', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Invisible', category: 'Taylor Swift', type: 'Song title' },
        { text: 'A Perfectly Good Heart', category: 'Taylor Swift', type: 'Song title' },
        { text: 'I Heart ?', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Debut', category: 'Taylor Swift', type: 'Song title' },
        { text: 'Georgia Stars', category: 'Taylor Swift', type: 'Lyrics' },
        { text: 'My Favorite Song', category: 'Taylor Swift', type: 'Lyrics' },
        { text: 'Old Pickup Truck', category: 'Taylor Swift', type: 'Lyrics' },
        { text: 'Just A Girl', category: 'Taylor Swift', type: 'Lyrics' },
        { text: 'Ill Be Strong', category: 'Taylor Swift', type: 'Lyrics' },
        { text: 'Just So Funny', category: 'Taylor Swift', type: 'Lyrics' },
        { text: 'On A Wishing Star', category: 'Taylor Swift', type: 'Lyrics' },
        { text: 'State The Obvious', category: 'Taylor Swift', type: 'Lyrics' },
        { text: 'Ur', category: 'Taylor Swift', type: 'Lyrics' },

        { text: 'Fearless', category: 'Fearless', type:"Album title" },
        { text: 'Fifteen', category: 'Fearless', type: 'Song Title' },
        { text: 'Love Story', category: 'Fearless', type: 'Song Title' },
        { text: 'Hey Stephen', category: 'Fearless', type: 'Song Title' },
        { text: 'White Horse', category: 'Fearless', type: 'Song Title' },
        { text: 'You Belong With Me', category: 'Fearless', type: 'Song Title' },
        { text: 'Breathe', category: 'Fearless', type: 'Song Title' },
        { text: 'Tell Me Why', category: 'Fearless', type: 'Song Title' },
        { text: 'Youre Not Sorry', category: 'Fearless', type: 'Song Title' },
        { text: 'The Way I Loved You', category: 'Fearless', type: 'Song Title' },
        { text: 'Forever & Always', category: 'Fearless', type: 'Song Title' },
        { text: 'The Best Day', category: 'Fearless', type: 'Song Title' },
        { text: 'Change', category: 'Fearless', type: 'Song Title' },
        { text: 'Jump Then Fall', category: 'Fearless', type: 'Song Title' },
        { text: 'Untouchable', category: 'Fearless', type: 'Song Title' },
        { text: 'Superstar', category: 'Fearless', type: 'Song Title' },
        { text: 'The Other Side Of The Door', category: 'Fearless', type: 'Song Title' },
        { text: 'Today Was A Fairytale', category: 'Fearless', type: 'Song Title' },
        { text: 'You All Over Me', category: 'Fearless', type: 'Song Title' },
        { text: 'Mr Perfectly Fine', category: 'Fearless', type: 'Song Title' },
        { text: 'We Were Happy', category: 'Fearless', type: 'Song Title' },
        { text: 'Thats When', category: 'Fearless', type: 'Song Title' },
        { text: 'Dont You', category: 'Fearless', type: 'Song Title' },
        { text: 'Bye Bye Baby', category: 'Fearless', type: 'Song Title' },
        { text: 'Just Say Yes', category: 'Fearless', type: 'Lyrics' },
        { text: 'Kissin in the Rain', category: 'Fearless', type: 'Lyrics' },
        { text: 'Cheer Captain', category: 'Fearless', type: 'Lyrics' },
        { text: 'On the Bleachers', category: 'Fearless', type: 'Lyrics' },
        { text: 'With You Id Dance', category: 'Fearless', type: 'Lyrics' },
        { text: 'Headfirst (Fearless)', category: 'Fearless', type: 'Lyrics' },
        { text: 'Capture It', category: 'Fearless', type: 'Lyrics' },
        { text: 'Remember It', category: 'Fearless', type: 'Lyrics' },
        { text: 'In my best dress', category: 'Fearless', type: 'Lyrics' },
        { text: 'Close Your Eyes', category: 'Fearless', type: 'Lyrics' },
        { text: 'Marry Me Juliet', category: 'Fearless', type: 'Lyrics' },
        { text: 'Feel This Magic', category: 'Fearless', type: 'Lyrics' },
        { text: 'Back up Baby', category: 'Fearless', type: 'Lyrics' },
        { text: 'Once Upon a Time', category: 'Fearless', type: 'Lyrics' },
        { text: 'Ms Misery', category: 'Fearless', type: 'Lyrics' },

        { text: 'Speak Now', category: 'Speak Now', type: 'Album title' },
        { text: 'Mine', category: 'Speak Now', type: 'Song title' },
        { text: 'Sparks Fly', category: 'Speak Now', type: 'Song title' },
        { text: 'Back To December', category: 'Speak Now', type: 'Song title' },
        { text: 'Dear John', category: 'Speak Now', type: 'Song title' },
        { text: 'Mean', category: 'Speak Now', type: 'Song title' },
        { text: 'The Story Of Us', category: 'Speak Now', type: 'Song title' },
        { text: 'Never Grow Up', category: 'Speak Now', type: 'Song title' },
        { text: 'Enchanted', category: 'Speak Now', type: 'Song title' },
        { text: 'Better Than Revenge', category: 'Speak Now', type: 'Song title' },
        { text: 'Innocent', category: 'Speak Now', type: 'Song title' },
        { text: 'Haunted', category: 'Speak Now', type: 'Song title' },
        { text: 'Last Kiss', category: 'Speak Now', type: 'Song title' },
        { text: 'Long Live', category: 'Speak Now', type: 'Song title' },
        { text: 'Ours', category: 'Speak Now', type: 'Song title' },
        { text: 'If This Was A Movie', category: 'Speak Now', type: 'Song title' },
        { text: 'Superman', category: 'Speak Now', type: 'Song title' },
        { text: 'Next Chapter', category: 'Speak Now', type: 'Lyrics' },
        { text: 'I Hope They Shine', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Remember this Feelin', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Careful Daughter', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Drop Everything Now', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Even Better', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Lights Go Wild', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Soft and Slow', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Fireworks Show', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Wishful Thinking', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Dont Say Yes', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Big Old City', category: 'Speak Now', type: 'Lyrics' },
        { text: 'Wildfire Lies', category: 'Speak Now', type: 'Lyrics' },

        { text: 'Red', category: 'Red', type: 'Album Title' },
        { text: 'State Of Grace', category: 'Red', type: 'Song Title' },
        { text: 'Treacherous', category: 'Red', type: 'Song Title' },
        { text: 'I Knew You Were Trouble (IKYWT)', category: 'Red', type: 'Song Title' },
        { text: 'All Too Well', category: 'Red', type: 'Song Title' },
        { text: '22', category: 'Red', type: 'Song Title' },
        { text: 'I Almost Do', category: 'Red', type: 'Song Title' },
        { text: 'We Are Never Ever Getting Back Together (WANEGBT)', category: 'Red', type: 'Song Title' },
        { text: 'Stay Stay Stay', category: 'Red', type: 'Song Title' },
        { text: 'Holy Ground', category: 'Red', type: 'Song Title' },
        { text: 'Sad Beautiful Tragic', category: 'Red', type: 'Song Title' },
        { text: 'The Lucky One', category: 'Red', type: 'Song Title' },
        { text: 'Everything Has Changed', category: 'Red', type: 'Song Title' },
        { text: 'Starlight', category: 'Red', type: 'Song Title' },
        { text: 'Begin Again', category: 'Red', type: 'Song Title' },
        { text: 'The Moment I Knew', category: 'Red', type: 'Song Title' },
        { text: 'Come Back Be Here', category: 'Red', type: 'Song Title' },
        { text: 'Girl At Home', category: 'Red', type: 'Song Title' },
        { text: 'Nothing New', category: 'Red', type: 'Song Title' },
        { text: 'Babe', category: 'Red', type: 'Song Title' },
        { text: 'Message In A Bottle', category: 'Red', type: 'Song Title' },
        { text: 'Forever Winter', category: 'Red', type: 'Song Title' },
        { text: 'Tore It All Up', category: 'Red', type: 'Lyrics' },
        { text: 'Casually Cruel', category: 'Red', type: 'Lyrics' },
        { text: 'Dream Impossible', category: 'Red', type: 'Lyrics' },
        { text: 'It was Rare', category: 'Red', type: 'Lyrics' },
        { text: 'I was there', category: 'Red', type: 'Lyrics' },
        { text: 'Twin Fire Signs', category: 'Red', type: 'Lyrics' },
        { text: 'Burnin Red', category: 'Red', type: 'Lyrics' },
        { text: 'Passionate as Sin', category: 'Red', type: 'Lyrics' },
        { text: 'Loving Him Was Red', category: 'Red', type: 'Lyrics' },
        { text: 'Know You Better', category: 'Red', type: 'Lyrics' },
        { text: 'Made of Starlight', category: 'Red', type: 'Lyrics' },
        { text: 'Dressed to the 9s', category: 'Red', type: 'Lyrics' },
        { text: 'Autumn Leaves', category: 'Red', type: 'Lyrics' },
        { text: 'Not Fine At All', category: 'Red', type: 'Lyrics' },
        { text: 'Lovely Jewel', category: 'Red', type: 'Lyrics' },
        { text: 'Im in a New Hell', category: 'Red', type: 'Lyrics' },
        { text: 'Alls Well That Ends Well', category: 'Red', type: 'Lyrics' },

        { text: '1989', category: '1989', type: 'Album Title'},
        { text: 'Welcome To New York', category: '1989', type: 'Song Title' },
        { text: 'Blank Space', category: '1989', type: 'Song Title' },
        { text: 'Style', category: '1989', type: 'Song Title' },
        { text: 'Out Of The Woods', category: '1989', type: 'Song Title' },
        { text: 'All You Had To Do Was Stay', category: '1989', type: 'Song Title' },
        { text: 'Shake It Off', category: '1989', type: 'Song Title' },
        { text: 'I Wish You Would', category: '1989', type: 'Song Title' },
        { text: 'Bad Blood', category: '1989', type: 'Song Title' },
        { text: 'Wildest Dreams', category: '1989', type: 'Song Title' },
        { text: 'How You Get The Girl', category: '1989', type: 'Song Title' },
        { text: 'This Love', category: '1989', type: 'Song Title' },
        { text: 'I Know Places', category: '1989', type: 'Song Title' },
        { text: 'Clean', category: '1989', type: 'Song Title' },
        { text: 'Wonderland', category: '1989', type: 'Song Title' },
        { text: 'You Are In Love', category: '1989', type: 'Song Title' },
        { text: 'New Romantics', category: '1989', type: 'Song Title' },
        { text: 'Its Been Waiting 4 U', category: '1989', type: 'Lyrics' },
        { text: 'Red Lip Classic', category: '1989', type: 'Lyrics' },
        { text: 'Burnin It Down', category: '1989', type: 'Lyrics' },
        { text: 'James Dean Daydream', category: '1989', type: 'Lyrics' },
        { text: 'In the Silence ♡', category: '1989', type: 'Lyrics' },
        { text: 'Drunk on Jealousy', category: '1989', type: 'Lyrics' },
        { text: 'U ♡ The Game', category: '1989', type: 'Lyrics' },
        { text: 'Down In Flames', category: '1989', type: 'Lyrics' },
        { text: 'Im Insane', category: '1989', type: 'Lyrics' },
        { text: 'Good Girl Faith', category: '1989', type: 'Lyrics' },
        { text: 'Take Me Home', category: '1989', type: 'Lyrics' },
        { text: 'R We Out Of The Woods', category: '1989', type: 'Lyrics' },
        { text: 'Nothin in my Brain', category: '1989', type: 'Lyrics' },
        { text: 'Haters Gonna Hate', category: '1989', type: 'Lyrics' },
        { text: 'Players Gonna Play', category: '1989', type: 'Lyrics' },
        { text: 'This Sick Beat', category: '1989', type: 'Lyrics' },
        { text: 'OMG', category: '1989', type: 'Lyrics' },
        { text: 'Mad Love', category: '1989', type: 'Lyrics' },
        { text: 'Live With Ghosts', category: '1989', type: 'Lyrics' },
        { text: 'Handsome as Hell', category: '1989', type: 'Lyrics' },
        { text: 'Forever and Ever', category: '1989', type: 'Lyrics' },
        { text: 'Its So Romantic', category: '1989', type: 'Lyrics' },

        { text: 'Reputation', category: 'Reputation', type: 'Album Title'},
        { text: 'Ready For It?', category: 'Reputation', type: 'Song Title' },
        { text: 'End Game', category: 'Reputation', type: 'Song Title' },
        { text: 'I Did Something Bad', category: 'Reputation', type: 'Song Title' },
        { text: 'Dont Blame Me', category: 'Reputation', type: 'Song Title' },
        { text: 'Delicate', category: 'Reputation', type: 'Song Title' },
        { text: 'Look What You Made Me Do', category: 'Reputation', type: 'Song Title' },
        { text: 'So It Goes...', category: 'Reputation', type: 'Song Title' },
        { text: 'Gorgeous', category: 'Reputation', type: 'Song Title' },
        { text: 'Getaway Car', category: 'Reputation', type: 'Song Title' },
        { text: 'King Of My Heart', category: 'Reputation', type: 'Song Title' },
        { text: 'Dancing With Our Hands Tied', category: 'Reputation', type: 'Song Title' },
        { text: 'Dress', category: 'Reputation', type: 'Song Title' },
        { text: 'This Is Why We Cant Have Nice Things', category: 'Reputation', type: 'Song Title' },
        { text: 'Call It What You Want', category: 'Reputation', type: 'Song Title' },
        { text: 'New Years Day', category: 'Reputation', type: 'Song Title' },
        { text: 'Keep Him 4Ever', category: 'Reputation', type: 'Lyrics' },
        { text: 'Island Breeze', category: 'Reputation', type: 'Lyrics' },
        { text: 'Lights Down Low', category: 'Reputation', type: 'Lyrics' },
        { text: 'Let The Games Begin', category: 'Reputation', type: 'Lyrics' },
        { text: 'In My Dreams', category: 'Reputation', type: 'Lyrics' },
        { text: 'Big Reputation', category: 'Reputation', type: 'Lyrics' },
        { text: 'I Dont ♡ The Drama It ♡ Me', category: 'Reputation', type: 'Lyrics' },
        { text: 'Light Me Up', category: 'Reputation', type: 'Lyrics' },
        { text: '♡ Made Me Crazy', category: 'Reputation', type: 'Lyrics' },
        { text: 'My Drug Is My Baby', category: 'Reputation', type: 'Lyrics' },
        { text: 'Now Im Ur Daisy', category: 'Reputation', type: 'Lyrics' },
        { text: 'Isnt It', category: 'Reputation', type: 'Lyrics' },
        { text: 'Another Drama', category: 'Reputation', type: 'Lyrics' },
        { text: 'All I Think About Is Karma', category: 'Reputation', type: 'Lyrics' },
        { text: 'Cause Shes Dead', category: 'Reputation', type: 'Lyrics' },
        { text: 'All Eyes On Us', category: 'Reputation', type: 'Lyrics' },
        { text: 'Home 2 My Cats', category: 'Reputation', type: 'Lyrics' },
        { text: 'Worst of Crimes', category: 'Reputation', type: 'Lyrics' },
        { text: 'Bonnie And Clyde', category: 'Reputation', type: 'Lyrics' },
        { text: 'U Fancy Me', category: 'Reputation', type: 'Lyrics' },
        { text: 'Not Fancy Stuff', category: 'Reputation', type: 'Lyrics' },
        { text: 'All At Once', category: 'Reputation', type: 'Lyrics' },
        { text: '♡ You In Secret', category: 'Reputation', type: 'Lyrics' },
        { text: 'Want Ur Midnights', category: 'Reputation', type: 'Lyrics' },
        { text: 'Dancing Witch', category: 'Reputation', type: 'Lyrics' },
        { text: 'Bad Feeling', category: 'Reputation', type: 'Lyrics' },
        { text: 'Loved U N Secret', category: 'Reputation', type: 'Lyrics' },
        { text: 'Your Illusionist', category: 'Reputation', type: 'Lyrics' },
        { text: 'Starry Eyes', category: 'Reputation', type: 'Lyrics' },

        { text: 'Lover', category: 'Lover', type: 'Album Title' },
        { text: 'I Forgot That You Existed', category: 'Lover', type: 'Song title' },
        { text: 'Cruel Summer', category: 'Lover', type: 'Song title' },
        { text: 'The Man', category: 'Lover', type: 'Song title' },
        { text: 'The Archer', category: 'Lover', type: 'Song title' },
        { text: 'I Think He Knows', category: 'Lover', type: 'Song title' },
        { text: 'Miss Americana & The Heartbreak Prince', category: 'Lover', type: 'Song title' },
        { text: 'Paper Rings', category: 'Lover', type: 'Song title' },
        { text: 'Cornelia Street', category: 'Lover', type: 'Song title' },
        { text: 'Death By A Thousand Cuts (DBATC)', category: 'Lover', type: 'Song title' },
        { text: 'London Boy', category: 'Lover', type: 'Song title' },
        { text: 'Soon Youll Get Better', category: 'Lover', type: 'Song title' },
        { text: 'False God', category: 'Lover', type: 'Song title' },
        { text: 'You Need To Calm Down (YNTCD)', category: 'Lover', type: 'Song title' },
        { text: 'Afterglow', category: 'Lover', type: 'Song title' },
        { text: 'Me!', category: 'Lover', type: 'Song title' },
        { text: 'Its Nice To Have A Friend (INTHAF)', category: 'Lover', type: 'Song title' },
        { text: 'Daylight', category: 'Lover', type: 'Song title' },
        { text: 'All The Girls U ♡ B4', category: 'Lover', type: 'Song title' },
        { text: 'Need', category: 'Lover', type: 'Song title' },
        { text: 'Can I Go Where U Go', category: 'Lover', type: 'Lyrics' },
        { text: 'Me Hee Hee', category: 'Lover', type: 'Lyrics' },
        { text: 'Je Suis Calme', category: 'Lover', type: 'Lyrics' },
        { text: 'IDK', category: 'Lover', type: 'Lyrics' },
        { text: 'Only See Daylight', category: 'Lover', type: 'Lyrics' },
        { text: 'U R What U ♡', category: 'Lover', type: 'Lyrics' },
        { text: 'Golden Like Daylight', category: 'Lover', type: 'Lyrics' },
        { text: 'Shiny Things', category: 'Lover', type: 'Lyrics' },
        { text: 'Ready 4 Combat', category: 'Lover', type: 'Lyrics' },
        { text: 'Long Time Comin', category: 'Lover', type: 'Lyrics' },
        { text: 'My Whole World', category: 'Lover', type: 'Lyrics' },
        { text: 'Dress 2 Kill', category: 'Lover', type: 'Lyrics' },
        { text: 'I Fancy U', category: 'Lover', type: 'Lyrics' },
        { text: 'In My Feelings', category: 'Lover', type: 'Lyrics' },
        { text: 'Devils Roll The Dice', category: 'Lover', type: 'Lyrics' },
        { text: 'Angels Roll Their Eyes', category: 'Lover', type: 'Lyrics' },
        { text: 'Bitch Not a Baller', category: 'Lover', type: 'Lyrics' },
        { text: 'Who Could Stay', category: 'Lover', type: 'Lyrics' },
        { text: 'He Got My ♡ Beat', category: 'Lover', type: 'Lyrics' },
        { text: 'No One Understands', category: 'Lover', type: 'Lyrics' },
        { text: 'Bless My Soul', category: 'Lover', type: 'Lyrics' },
        { text: 'Follow The Sparks', category: 'Lover', type: 'Lyrics' },
        { text: 'Lyrical Smile', category: 'Lover', type: 'Lyrics' },
        { text: 'The Moon Is High', category: 'Lover', type: 'Lyrics' },
        { text: 'My Time My Wine', category: 'Lover', type: 'Lyrics' },
        { text: 'Im NYC', category: 'Lover', type: 'Lyrics' },
        { text: 'Youre The West Village', category: 'Lover', type: 'Lyrics' },
        { text: 'Worship this ♡', category: 'Lover', type: 'Lyrics' },
        { text: 'Ur Being 2 Loud', category: 'Lover', type: 'Lyrics' },

        { text: 'Folklore', category: 'Folklore', type: 'Album Title' },
        { text: 'The 1', category: 'Folklore', type: 'Song Title' },
        { text: 'Cardigan', category: 'Folklore', type: 'Song Title' },
        { text: 'The Last Great American Dynasty', category: 'Folklore', type: 'Song Title' },
        { text: 'Exile', category: 'Folklore', type: 'Song Title' },
        { text: 'My Tears Ricochet', category: 'Folklore', type: 'Song Title' },
        { text: 'Mirrorball', category: 'Folklore', type: 'Song Title' },
        { text: 'Seven', category: 'Folklore', type: 'Song Title' },
        { text: 'August', category: 'Folklore', type: 'Song Title' },
        { text: 'This Is Me Trying', category: 'Folklore', type: 'Song Title' },
        { text: 'Illicit Affairs', category: 'Folklore', type: 'Song Title' },
        { text: 'Invisible String', category: 'Folklore', type: 'Song Title' },
        { text: 'Mad Woman', category: 'Folklore', type: 'Song Title' },
        { text: 'Epiphany', category: 'Folklore', type: 'Song Title' },
        { text: 'Betty', category: 'Folklore', type: 'Song Title' },
        { text: 'Peace', category: 'Folklore', type: 'Song Title' },
        { text: 'Hoax', category: 'Folklore', type: 'Song Title' },
        { text: 'The Lakes', category: 'Folklore', type: 'Song Title' },
        { text: '♡ U 2 the Moon and 2 Saturn', category: 'Folklore', type: 'Lyrics' },
        { text: 'On Some New Shit', category: 'Folklore', type: 'Lyrics' },
        { text: 'Auroras and Sad Prose', category: 'Folklore', type: 'Lyrics' },
        { text: 'Marvelous Time', category: 'Folklore', type: 'Lyrics' },
        { text: 'Ruining Everything', category: 'Folklore', type: 'Lyrics' },
        { text: 'Sequin Smile', category: 'Folklore', type: 'Lyrics' },
        { text: 'Give U My Wild', category: 'Folklore', type: 'Lyrics' },
        { text: 'Peter Losing Wendy', category: 'Folklore', type: 'Lyrics' },
        { text: 'Key Lime Green', category: 'Folklore', type: 'Lyrics' },
        { text: 'Bitch Pack Friends', category: 'Folklore', type: 'Lyrics' },
        { text: 'Miss Me N Ur Bones', category: 'Folklore', type: 'Lyrics' },
        { text: 'Stolen Lullabies', category: 'Folklore', type: 'Lyrics' },
        { text: 'Tallest Tiptoes', category: 'Folklore', type: 'Lyrics' },
        { text: 'Not Like The Regulars', category: 'Folklore', type: 'Lyrics' },
        { text: 'High in the Sky', category: 'Folklore', type: 'Lyrics' },
        { text: 'Sweet Tea N The Summer', category: 'Folklore', type: 'Lyrics' },
        { text: 'Salt Air', category: 'Folklore', type: 'Lyrics' },
        { text: 'August Slipped Away', category: 'Folklore', type: 'Lyrics' },
        { text: 'Never Mine', category: 'Folklore', type: 'Lyrics' },
        { text: 'The Hope of it All', category: 'Folklore', type: 'Lyrics' },
        { text: 'Summer ♡', category: 'Folklore', type: 'Lyrics' },
        { text: 'Ahead of the Curve', category: 'Folklore', type: 'Lyrics' },
        { text: 'Dont Call Me Baby', category: 'Folklore', type: 'Lyrics' },
        { text: 'Idiotic Fool', category: 'Folklore', type: 'Lyrics' },
        { text: 'Just So Pretty', category: 'Folklore', type: 'Lyrics' },
        { text: 'Mystical Time', category: 'Folklore', type: 'Lyrics' },
        { text: 'Purple Pink Skies', category: 'Folklore', type: 'Lyrics' },
        { text: 'Scorpion Sting', category: 'Folklore', type: 'Lyrics' },
        { text: 'Fuck U 4Ever', category: 'Folklore', type: 'Lyrics' },
        { text: 'U Made Her Like That', category: 'Folklore', type: 'Lyrics' },
        { text: 'Would U Have Me', category: 'Folklore', type: 'Lyrics' },
        { text: 'Would U Want Me', category: 'Folklore', type: 'Lyrics' },
        { text: 'Im a Fire', category: 'Folklore', type: 'Lyrics' },
        { text: 'Ocean Wave Blues', category: 'Folklore', type: 'Lyrics' },

        { text: 'Evermore', category: 'Evermore', type: 'Album Title' },
        { text: 'Willow', category: 'Evermore', type: 'Song Title' },
        { text: 'Champagne Problems', category: 'Evermore', type: 'Song Title' },
        { text: 'Gold Rush', category: 'Evermore', type: 'Song Title' },
        { text: 'Tis The Damn Season', category: 'Evermore', type: 'Song Title' },
        { text: 'Tolerate It', category: 'Evermore', type: 'Song Title' },
        { text: 'No Body, No Crime', category: 'Evermore', type: 'Song Title' },
        { text: 'Happiness', category: 'Evermore', type: 'Song Title' },
        { text: 'Dorothea', category: 'Evermore', type: 'Song Title' },
        { text: 'Coney Island', category: 'Evermore', type: 'Song Title' },
        { text: 'Ivy', category: 'Evermore', type: 'Song Title' },
        { text: 'Cowboy Like Me', category: 'Evermore', type: 'Song Title' },
        { text: 'Long Story Short', category: 'Evermore', type: 'Song Title' },
        { text: 'Marjorie', category: 'Evermore', type: 'Song Title' },
        { text: 'Closure', category: 'Evermore', type: 'Song Title' },
        { text: 'Evermore', category: 'Evermore', type: 'Song Title' },
        { text: 'Right Where You Left Me', category: 'Evermore', type: 'Song Title' },
        { text: 'Its Time To Go', category: 'Evermore', type: 'Song Title' },
        { text: 'He Did It', category: 'Evermore', type: 'Lyrics' },
        { text: 'Sweetest Con', category: 'Evermore', type: 'Lyrics' },
        { text: 'Wreck My Plans', category: 'Evermore', type: 'Lyrics' },
        { text: 'Fucked In The Head', category: 'Evermore', type: 'Lyrics' },
        { text: '90s Trend', category: 'Evermore', type: 'Lyrics' },
        { text: 'Gardens of Babylon', category: 'Evermore', type: 'Lyrics' },
        { text: 'I survived', category: 'Evermore', type: 'Lyrics' },
        { text: 'Youre Speechless', category: 'Evermore', type: 'Lyrics' },
        { text: 'November Flush', category: 'Evermore', type: 'Lyrics' },
        { text: 'Gleaming', category: 'Evermore', type: 'Lyrics' },
        { text: 'Twinkling', category: 'Evermore', type: 'Lyrics' },
        { text: 'Double Vision', category: 'Evermore', type: 'Lyrics' },
        { text: 'Rose Blush', category: 'Evermore', type: 'Lyrics' },
        { text: 'Babe 4 The Weekend', category: 'Evermore', type: 'Lyrics' },
        { text: 'In My Hometown', category: 'Evermore', type: 'Lyrics' },
        { text: 'Fancy Shit', category: 'Evermore', type: 'Lyrics' },
        { text: 'Olive Garden', category: 'Evermore', type: 'Lyrics' },
        { text: 'Beautiful Fool', category: 'Evermore', type: 'Lyrics' },
        { text: 'Shiny Friends', category: 'Evermore', type: 'Lyrics' },
        { text: 'Happy Birthday', category: 'Evermore', type: 'Lyrics' },
        { text: 'Did I Shatter You', category: 'Evermore', type: 'Lyrics' },
        { text: 'Bright Lights', category: 'Evermore', type: 'Lyrics' },
        { text: 'My Centerfold', category: 'Evermore', type: 'Lyrics' },
        { text: 'Over and Over', category: 'Evermore', type: 'Lyrics' },
        { text: 'Bluest Skies', category: 'Evermore', type: 'Lyrics' },
        { text: 'Oh Goddamn', category: 'Evermore', type: 'Lyrics' },
        { text: 'In My Dreamland', category: 'Evermore', type: 'Lyrics' },
        { text: 'Covered in U', category: 'Evermore', type: 'Lyrics' },
        { text: 'Dangerous Game', category: 'Evermore', type: 'Lyrics' },
        { text: 'Never Gonna Love Again', category: 'Evermore', type: 'Lyrics' },
        { text: 'Bandit Like Me', category: 'Evermore', type: 'Lyrics' },
        { text: 'Eyes Full of Stars', category: 'Evermore', type: 'Lyrics' },
        { text: 'Im All About U', category: 'Evermore', type: 'Lyrics' },
        { text: 'Youre Alive', category: 'Evermore', type: 'Lyrics' },
        { text: 'Im Doin Better', category: 'Evermore', type: 'Lyrics' },
        { text: 'My Tears and My Beers', category: 'Evermore', type: 'Lyrics' },
        { text: 'Rumors Fly', category: 'Evermore', type: 'Lyrics' },
        { text: 'Stay Here 4Ever', category: 'Evermore', type: 'Lyrics' },

        { text: 'Midnights', category: 'Midnights', type: 'Album Title' },
        { text: 'Lavender Haze', category: 'Midnights', type: 'Song Title' },
        { text: 'Anti Hero', category: 'Midnights', type: 'Song Title' },
        { text: 'Your On Your Own Kid (YOYOK)', category: 'Midnights', type: 'Song Title' },
        { text: 'Question', category: 'Midnights', type: 'Song Title' },
        { text: 'Bejeweled', category: 'Midnights', type: 'Song Title' },
        { text: 'Karma', category: 'Midnights', type: 'Song Title' },
        { text: 'Maroon', category: 'Midnights', type: 'Song Title' },
        { text: 'Snow On The Beach', category: 'Midnights', type: 'Song Title' },
        { text: 'Midnight Rain', category: 'Midnights', type: 'Song Title' },
        { text: 'Vigilante Shit', category: 'Midnights', type: 'Song Title' },
        { text: 'Labyrinth', category: 'Midnights', type: 'Song Title' },
        { text: 'Glitch', category: 'Midnights', type: 'Song Title' },
        { text: 'High Infidelity', category: 'Midnights', type: 'Song Title' },
        { text: 'The Great War', category: 'Midnights', type: 'Song Title' },
        { text: 'Bigger Than The Whole Sky', category: 'Midnights', type: 'Song Title' },
        { text: 'Paris', category: 'Midnights', type: 'Song Title' },
        { text: 'Dear Reader', category: 'Midnights', type: 'Song Title' },
        { text: 'Sweet Nothing', category: 'Midnights', type: 'Song Title' },
        { text: 'Blood Moonlit', category: 'Midnights', type: 'Lyrics' },
        { text: '2 Soft 4 All of It', category: 'Midnights', type: 'Lyrics' },
        { text: 'Its Me Hi', category: 'Midnights', type: 'Lyrics' },
        { text: 'Im The Problem', category: 'Midnights', type: 'Lyrics' },
        { text: 'I Miss Sparkling', category: 'Midnights', type: 'Lyrics' },
        { text: 'Karma Is a Cat', category: 'Midnights', type: 'Lyrics' },
        { text: 'Karma Is My BF', category: 'Midnights', type: 'Lyrics' },
        { text: 'Real Fuckin Legacy', category: 'Midnights', type: 'Lyrics' },
        { text: 'Are We Falling', category: 'Midnights', type: 'Lyrics' },
        { text: 'Love Blackout', category: 'Midnights', type: 'Lyrics' },
        { text: 'April 29', category: 'Midnights', type: 'Lyrics' },
        { text: 'Meet Me At Midnight', category: 'Midnights', type: 'Lyrics' },
        { text: 'Shimmer', category: 'Midnights', type: 'Lyrics' },
        { text: 'Dressing 4 Revenge', category: 'Midnights', type: 'Lyrics' },
        { text: 'I Dont Remember', category: 'Midnights', type: 'Lyrics' },
        { text: 'My Auras Moonstone', category: 'Midnights', type: 'Lyrics' },
        { text: '2003 Unbearable', category: 'Midnights', type: 'Lyrics' },
        { text: 'Get It Off My Desk', category: 'Midnights', type: 'Lyrics' },
        { text: 'Go Viral', category: 'Midnights', type: 'Lyrics' },
        { text: 'Love Spiral', category: 'Midnights', type: 'Lyrics' },
        { text: 'So Scarlet', category: 'Midnights', type: 'Lyrics' },
        { text: 'Sexy Baby', category: 'Midnights', type: 'Lyrics' },
        { text: 'Monster on the Hill', category: 'Midnights', type: 'Lyrics' },
        { text: 'At Tea Time', category: 'Midnights', type: 'Lyrics' },
        { text: 'Everybody Agrees', category: 'Midnights', type: 'Lyrics' },
        { text: 'All 4 U Like Janet', category: 'Midnights', type: 'Lyrics' },
        { text: 'Weird', category: 'Midnights', type: 'Lyrics' },
        { text: 'Fuckin Beautiful', category: 'Midnights', type: 'Lyrics' },
        { text: 'U Always Have Been', category: 'Midnights', type: 'Lyrics' },
        { text: 'Take the Moment', category: 'Midnights', type: 'Lyrics' },
        { text: 'Peppermint Candy', category: 'Midnights', type: 'Lyrics' },
        { text: 'He was Sunshine', category: 'Midnights', type: 'Lyrics' },
        { text: 'Midnights like This', category: 'Midnights', type: 'Lyrics' },
        { text: 'Half Moon Eyes', category: 'Midnights', type: 'Lyrics' },
        { text: 'Bad Surprise', category: 'Midnights', type: 'Lyrics' },
        { text: 'Looks Can Kill', category: 'Midnights', type: 'Lyrics' },
        { text: 'I Dont Dress 4 Men', category: 'Midnights', type: 'Lyrics' },
        { text: 'I Dont Dress 4 Women', category: 'Midnights', type: 'Lyrics' },
        { text: 'I Dont Start Shit', category: 'Midnights', type: 'Lyrics' },
        { text: 'Get Even', category: 'Midnights', type: 'Lyrics' },
        { text: 'Sweet Kind Fun', category: 'Midnights', type: 'Lyrics' },
        { text: 'Shut Up Wench', category: 'Midnights', type: 'Lyrics' },
        { text: 'Im Gonna Be Hungover', category: 'Midnights', type: 'Lyrics' },
        { text: 'Going Out Tonight', category: 'Midnights', type: 'Lyrics' },
        { text: 'Diamonds N My Eyes', category: 'Midnights', type: 'Lyrics' },
        { text: 'Nice', category: 'Midnights', type: 'Lyrics' },
        { text: 'Sapphire Tears', category: 'Midnights', type: 'Lyrics' },
        { text: 'Whats a Girl Gonna Do', category: 'Midnights', type: 'Lyrics' },
        { text: 'Breathe In', category: 'Midnights', type: 'Lyrics' },
        { text: 'Breathe Deep', category: 'Midnights', type: 'Lyrics' },
        { text: 'Sweet Like Honey', category: 'Midnights', type: 'Lyrics' },
        { text: 'Arent U Envious', category: 'Midnights', type: 'Lyrics' },
        { text: 'Me And Karma Vibe', category: 'Midnights', type: 'Lyrics' },
        { text: 'All By Design', category: 'Midnights', type: 'Lyrics' },
        { text: 'Always Remember', category: 'Midnights', type: 'Lyrics' },
        { text: 'Taken By the View', category: 'Midnights', type: 'Lyrics' },
        { text: 'Put On Your Records', category: 'Midnights', type: 'Lyrics' },
        { text: 'Im Not Even Sorry', category: 'Midnights', type: 'Lyrics' },
        { text: 'Nights R So Starry', category: 'Midnights', type: 'Lyrics' },
        { text: 'Scared of Ghosts', category: 'Midnights', type: 'Lyrics' },
        { text: 'U Should Find Another', category: 'Midnights', type: 'Lyrics' },
        { text: 'I Shine So Bright', category: 'Midnights', type: 'Lyrics' },    

        { text: 'The Tortured Poets Department', category: 'Tortured', type: 'Album Title' },
        { text: 'Fortnight', category: 'Tortured', type: 'Song Title' },
        { text: 'My Boy Only Breaks His Favorite Toys', category: 'Tortured', type: 'Song Title' },
        { text: 'Down Bad', category: 'Tortured', type: 'Song Title' },
        { text: 'So Long, London', category: 'Tortured', type: 'Song Title' },
        { text: 'But Daddy I Love Him', category: 'Tortured', type: 'Song Title' },
        { text: 'Fresh Out the Slammer', category: 'Tortured', type: 'Song Title' },
        { text: 'Florida', category: 'Tortured', type: 'Song Title' },
        { text: 'Guilty as Sin', category: 'Tortured', type: 'Song Title' },
        { text: 'Whos Afraid of Little Old Me', category: 'Tortured', type: 'Song Title' },
        { text: 'I Can Fix Him', category: 'Tortured', type: 'Song Title' },
        { text: 'Loml', category: 'Tortured', type: 'Song Title' },
        { text: 'I Can Do It with a Broken Heart', category: 'Tortured', type: 'Song Title' },
        { text: 'The Black Dog', category: 'Tortured', type: 'Song Title' },
        { text: 'Imgonnagetyouback', category: 'Tortured', type: 'Song Title' },
        { text: 'The Albatross', category: 'Tortured', type: 'Song Title' },
        { text: 'Chloe or Sam or Sophia or Marcus', category: 'Tortured', type: 'Song Title' },
        { text: 'How Did It End', category: 'Tortured', type: 'Song Title' },
        { text: 'So High School', category: 'Tortured', type: 'Song Title' },
        { text: 'I Hate It Here', category: 'Tortured', type: 'Song Title' },
        { text: 'Thank You Aimee', category: 'Tortured', type: 'Song Title' },
        { text: 'I Look in Peoples Windows', category: 'Tortured', type: 'Song Title' },
        { text: 'The Prophecy', category: 'Tortured', type: 'Song Title' },
        { text: 'Cassandra', category: 'Tortured', type: 'Song Title' },
        { text: 'Peter', category: 'Tortured', type: 'Song Title' },
        { text: 'The Bolter', category: 'Tortured', type: 'Song Title' },
        { text: 'Robin', category: 'Tortured', type: 'Song Title' },
        { text: 'The Manuscript', category: 'Tortured', type: 'Song Title' },
       
        { text: 'In My Eras Era', category: 'Misc', type: 'Taylor Quote' },
        { text: '13 Braincells', category: 'Misc', type: 'Taylor Quote' },
        { text: 'Eras Tour', category: 'Misc' },
        { text: 'Eras', category: 'Misc' },
        { text: 'T-Swift', category: 'Misc' },
        { text: '1 2 3 Lets Go Bitch', category: 'Misc', type: 'Fan Chant' },
        { text: 'Becky', category: 'Misc', type: 'Meme' },
        { text: 'No Its Becky', category: 'Misc' },
        { text: 'Taylor Swift', category: 'Misc' },
        { text: '13', category: 'Misc', type: 'Favourite Number'},
        { text: 'My Mind Is Alive', category: 'Misc', type: 'Taylor Quote' },
        { text: 'TS', category: 'Misc' },
        { text: 'Taylors Version', category: 'Misc' },
        { text: 'Fuck Ticketmaster', category: 'Misc' },
        { text: 'Eyes Open', category: 'Misc' },
        { text: 'Safe and Sound', category: 'Misc' },
        { text: 'Crazier', category: 'Misc' },
        { text: 'Carolina', category: 'Misc' },
        { text: 'Renegade', category: 'Misc' },
        { text: 'Gasoline', category: 'Misc' },
        { text: 'I Dont Wanna Live 4Eva', category: 'Misc' },
        { text: 'Thug Story', category: 'Misc' },

      // Add more strings as needed
    ];
  
    strings.forEach(function(string) {
      var containsCharacters = characters.some(function(character) {
        return string.text.toLowerCase().includes(character.trim());
      });
  
      if (!containsCharacters) {
        if ((categoryTaylorSwift && string.category === 'Taylor Swift') ||
            (categoryFearless && string.category === 'Fearless') ||
            (categorySpeakNow && string.category === 'Speak Now') ||
            (categoryRed && string.category === 'Red') ||
            (category1989 && string.category === '1989') ||
            (categoryReputation && string.category === 'Reputation') ||
            (categoryLover && string.category === 'Lover') ||
            (categoryFolklore && string.category === 'Folklore') ||
            (categoryEvermore && string.category === 'Evermore') ||
            (categoryMidnights && string.category === 'Midnights') ||
            (categoryTortured && string.category === 'Tortured') ||
            (categoryMisc && string.category === 'Misc')
        ) 
            
            {
              resultsContainer.innerHTML += `<p><span>${string.text} </span>(${string.type} from the ${string.category} album)</p>`;        }
      }
    });
  }
  
  function selectAllCategories() {
    var categoryCheckboxes = document.querySelectorAll('input[type="checkbox"][id^="category"]');
    categoryCheckboxes.forEach(function(checkbox) {
      checkbox.checked = true;
    });
  }
  